# Generated by Django 4.2.16 on 2024-09-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section', models.CharField(max_length=80)),
                ('Key', models.CharField(max_length=100)),
                ('Value', models.CharField(max_length=1500)),
            ],
        ),
    ]
