# Generated by Django 4.2.16 on 2024-09-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyApp', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.FileField(default='null', upload_to='media/'),
        ),
    ]
