# Generated by Django 4.2.16 on 2024-09-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyApp', '0004_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Description',
            field=models.TextField(),
        ),
    ]
