# Generated by Django 4.2.15 on 2024-09-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Icon', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
    ]
