# Generated by Django 4.2.15 on 2024-09-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
