# Generated by Django 4.2.16 on 2024-09-27 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('Slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('Featured Image', models.FileField(upload_to='')),
                ('Created On', models.DateTimeField(auto_now_add=True)),
                ('Updated On', models.DateTimeField(auto_now=True)),
                ('publishedOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'ordering': ('-publishedOn',),
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Key', models.CharField(max_length=255)),
                ('Value', models.TextField()),
                ('Created On', models.DateTimeField()),
            ],
        ),
    ]
