# Generated by Django 4.2.16 on 2024-09-28 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Created On',
            new_name='createdOn',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Updated On',
            new_name='updatedOn',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='Created On',
            new_name='createdOn',
        ),
    ]
